apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-score
spec:
  ingressClassName: traefik
  rules:
    - host: wrong-credit.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-score
                port:
                  number: 80
